name: NZP Config
type: module
description: custom logic for nzp configuration management
package: Custom
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - config_ignore
  - config_filter
