name: Deploy to Pantheon
on:
  push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: deployer
      env:
        pantheon_repo: 'ssh://codeserver.dev.0793264a-5155-42a8-8f9e-c4d7a2dee9f9@codeserver.dev.0793264a-5155-42a8-8f9e-c4d7a2dee9f9.drush.in:2222/~/repository.git'
      run: |
        git remote add pantheon $pantheon_repo
        git config --global user.email "elkhatibm@si.edu"
        git config --global user.name "Mo El-Khatib"
        git add .
        git commit -q -m 'Build assets for dev.'
        git push -f pantheon master
